(function(){'use strict';
  const CI=window.CI;
  function dateKey(){return new Date().toISOString().slice(0,10);}
  function dayMissions(){const s=CI.state;if(s.missions.date!==String(s.day)){s.missions={date:String(s.day),claimed:[],base:{spins:s.spins,jobs:s.stats.jobs,businessBought:s.stats.businessBought,blackjackRounds:s.blackjackRounds}};}if(!s.missions.base)s.missions.base={spins:s.spins,jobs:s.stats.jobs,businessBought:s.stats.businessBought,blackjackRounds:s.blackjackRounds};const base=s.missions.base;return[
    {id:'spins',name:'Roztočte automat pětkrát',progress:Math.min(5,s.spins-base.spins),target:5,reward:180},
    {id:'work',name:'Odpracujte jednu směnu',progress:Math.min(1,s.stats.jobs-base.jobs),target:1,reward:220},
    {id:'business',name:'Pořiďte si městský podnik',progress:Math.min(1,s.stats.businessBought-base.businessBought),target:1,reward:450},
    {id:'blackjack',name:'Zahrajte tři kola blackjacku',progress:Math.min(3,s.blackjackRounds-base.blackjackRounds),target:3,reward:250}
  ]; }
  CI.render=()=>{
    const s=CI.state;CI.$('#credits').textContent=CI.money(s.credits);CI.$('#vip-level').textContent=CI.vipName().toLocaleUpperCase('cs-CZ');CI.$('#prestige').textContent=CI.money(s.prestige);
    CI.$('#slot-bet').textContent=CI.money(s.slotBet);CI.$('#slot-lines').textContent=s.slotLines;CI.$('#blackjack-bet').textContent=CI.money(s.blackjackBet);CI.$('#selected-chip').textContent=CI.money(s.selectedChip);
    CI.$('#owned-property').textContent=CI.propertyName();CI.$('#passive-income').textContent='+'+CI.money(CI.passiveIncome()+(CI.businessData()?.income||0))+' kr./den';CI.$('#owned-vehicle').textContent=CI.vehicleData().name;CI.$('#owned-business').textContent=CI.businessData()?.name||'Žádný';CI.$('#net-worth').textContent=CI.money(s.credits+CI.passiveIncome()*30+(CI.vehicleData().price||0)+(CI.businessData()?.price||0)+s.inventory.reduce((sum,item)=>sum+item.price,0));CI.$('#city-time').textContent='DEN '+s.day;CI.$('#day-phase').textContent=CI.dayCycle()==='DEN'?'JASNÝ DEN':'VEČERNÍ MĚSTO';CI.$('#clock-label').textContent=CI.dayCycle()==='DEN'?'DENNÍ SMĚNA':'VEČERNÍ SMĚNA';CI.$('#day-icon').textContent=CI.dayCycle()==='DEN'?'☀':'☾';CI.$('.map-car').title='Vaše vozidlo: '+CI.vehicleData().name;
    CI.$$('.world-button').forEach(b=>b.classList.toggle('active',b.dataset.world===(CI.world||'casino')));CI.$('#casino-world').classList.toggle('hidden',(CI.world||'casino')!=='casino');CI.$('#city-world').classList.toggle('hidden',(CI.world||'casino')!=='city');
    CI.$$('.district').forEach(b=>b.classList.toggle('district-owned',b.dataset.district===['stredni','stredni','bohata','bohata','centrum','centrum'][Math.min(s.property.index,5)]));CI.$('#payline').textContent='◆ '+s.slotLines+' AKTIVNÍCH LINIÍ ◆';
    if(CI.$('#player-score').textContent==='—'){['hit','stand','double','split','insurance'].forEach(a=>CI.$('[data-action="'+a+'"]').disabled=true);}
  };
  CI.missionsModal=()=>{
    const missions=dayMissions(),claims=CI.state.missions.claimed,rows=missions.map(m=>{const claimed=claims.includes(m.id),ready=m.progress>=m.target;return `<div class="mission-item"><span><b>${m.name}</b><br><small>Postup: ${m.progress}/${m.target} • Odměna ${CI.money(m.reward)} kr.</small></span><button class="${ready&&!claimed?'gold-button':'wood-button'}" data-claim="${m.id}" ${!ready||claimed?'disabled':''}>${claimed?'Hotovo':ready?'Vyzvednout':'Nesplněno'}</button></div>`;}).join('');
    const today=dateKey(),cash=CI.state.cashback;const weeklyKey=new Date().getFullYear()+'-'+Math.ceil((Date.now()-new Date(new Date().getFullYear(),0,1))/604800000);CI.modal('Mise a věrnostní odměny',`<p class="modal-copy">Městský den ${CI.state.day}. Splňte úkoly a vyzvedněte denní či týdenní bonus.</p>${rows}<h3>Věrnostní odměna</h3><div class="mission-item"><span>Denní cashback</span><button class="gold-button" data-cashback="daily" ${cash.dailyDate===today?'disabled':''}>${cash.dailyDate===today?'Vyzvednuto':'+50 kr.'}</button></div><div class="mission-item"><span>Týdenní cashback</span><button class="gold-button" data-cashback="weekly" ${cash.weeklyDate===weeklyKey?'disabled':''}>${cash.weeklyDate===weeklyKey?'Vyzvednuto':'+250 kr.'}</button></div>`);
    CI.$$('[data-claim]').forEach(b=>b.addEventListener('click',()=>{const m=missions.find(x=>x.id===b.dataset.claim);if(m&&m.progress>=m.target&&!CI.state.missions.claimed.includes(m.id)){CI.state.missions.claimed.push(m.id);CI.updateCredit(m.reward);CI.saveSilent();CI.render();CI.missionsModal();CI.toast('Mise splněna: +'+CI.money(m.reward)+' kreditů.','good');}}));
    CI.$$('[data-cashback]').forEach(b=>b.addEventListener('click',()=>{const which=b.dataset.cashback,stamp=which==='daily'?today:weeklyKey;if(CI.state.cashback[which+'Date']===stamp)return;CI.state.cashback[which+'Date']=stamp;CI.updateCredit(which==='daily'?50:250);CI.saveSilent();CI.render();CI.missionsModal();CI.toast('Věrnostní odměna byla připsána.','good');}));
  };
  CI.statisticsModal=()=>{const s=CI.state;CI.modal('Osobní statistiky',`<div class="stat-grid"><div class="stat-box"><small>Aktuální stav</small><b>${CI.money(s.credits)} kr.</b></div><div class="stat-box"><small>Úroveň VIP</small><b>${CI.vipName()}</b></div><div class="stat-box"><small>Automatová kola</small><b>${CI.money(s.spins)}</b></div><div class="stat-box"><small>Ruleta</small><b>${CI.money(s.rouletteRounds)} kol</b></div><div class="stat-box"><small>Blackjack</small><b>${CI.money(s.blackjackRounds)} kol</b></div><div class="stat-box"><small>Celkem vsazeno</small><b>${CI.money(s.casinoSpent)} kr.</b></div><div class="stat-box"><small>Výhry v kasinu</small><b>${CI.money(s.casinoWon)} kr.</b></div><div class="stat-box"><small>Nejvyšší výhra</small><b>${CI.money(s.stats.largestWin)} kr.</b></div><div class="stat-box"><small>Pracovní směny</small><b>${CI.money(s.stats.jobs)}</b></div><div class="stat-box"><small>Prestiž</small><b>${CI.money(s.prestige)}</b></div></div>`,[{label:'Zavřít',fn:close=>close()}]);};
  CI.settingsModal=()=>{
    const s=CI.state;CI.modal('Nastavení',`<div class="modal-row"><span>Zvukové efekty</span><button class="wood-button" id="sound-toggle">${s.settings.sound?'Zapnuto':'Vypnuto'}</button></div><label>Limit herních sázek za relaci<input class="modal-input" id="limit-input" type="number" min="100" max="1000000" value="${s.settings.responsibleLimit}"></label><div class="modal-row"><span>Pauza na zodpovědnou hru</span><b>${s.settings.cooldownUntil>Date.now()?Math.ceil((s.settings.cooldownUntil-Date.now())/60000)+' min.':'Nepoužita'}</b></div><p class="modal-copy">Nastavte vlastní limit nebo si dopřejte minutovou přestávku. Kasino není způsob, jak vydělávat peníze.</p><h3>Profil hráče</h3><button class="wood-button" id="profile-export">Zobrazit můj profilový kód</button><label>Kód jiného hráče<input class="modal-input" id="profile-code" placeholder="Vložte profilový kód"></label><button class="wood-button" id="profile-import">Přidat do mapy</button><div class="modal-actions-spacer"></div><button class="wood-button" id="export-save">Exportovat uloženou hru</button> <button class="wood-button" id="import-save">Importovat uloženou hru</button>`);
    CI.$('#sound-toggle').addEventListener('click',()=>{s.settings.sound=!s.settings.sound;CI.saveSilent();CI.settingsModal();});
    CI.$('#limit-input').addEventListener('change',e=>{s.settings.responsibleLimit=CI.checkedInteger(e.target.value,100,1000000);CI.saveSilent();CI.toast('Limit zodpovědné hry byl uložen.','good');});
    CI.$('#profile-export').addEventListener('click',async()=>{const profile={name:'Návštěvník '+String(s.prestige).padStart(2,'0'),property:CI.propertyName(),prestige:s.prestige,vehicle:CI.vehicleData().name},code=btoa(unescape(encodeURIComponent(JSON.stringify(profile))));const b=CI.$('#profile-code');b.value=code;b.select();try{await navigator.clipboard.writeText(code);CI.toast('Profilový kód byl zkopírován.','good');}catch(_){CI.toast('Profilový kód je připraven ke zkopírování.','');}});
    CI.$('#profile-import').addEventListener('click',()=>{try{const profile=JSON.parse(decodeURIComponent(escape(atob(CI.$('#profile-code').value.trim()))));if(!profile.name||typeof profile.prestige!=='number')throw new Error();s.rivals=(s.rivals||[]).filter(x=>x.name!==profile.name);s.rivals.push({name:String(profile.name).slice(0,40),property:String(profile.property||'Bydlení'),prestige:Math.max(0,profile.prestige),vehicle:String(profile.vehicle||'Vůz')});CI.saveSilent();CI.renderRivals();CI.toast('Profil byl přidán na mapu města.','good');}catch(_){CI.toast('Tento profilový kód není platný.','bad');}});
    CI.$('#export-save').addEventListener('click',CI.exportSave);CI.$('#import-save').addEventListener('click',()=>CI.$('#import-file').click());
  };
  CI.responsibleModal=()=>CI.modal('Zodpovědná hra',`<div class="limit-warning">Hrajte pouze pro zábavu. Sázky mohou být ztraceny. Nastavte si hranici, při které přestanete hrát.</div><p class="modal-copy">Váš limit: ${CI.money(CI.state.settings.responsibleLimit)} kr. • Vsazeno v této uložené hře: ${CI.money(CI.state.casinoSpent)} kr.</p><p class="modal-copy">Pauza na 60 sekund vám umožní vrátit se ke hře s čistou hlavou.</p>`,[{label:'Zahájit minutovou pauzu',kind:'gold-button',fn:close=>{CI.state.settings.cooldownUntil=Date.now()+60000;CI.saveSilent();close();CI.toast('Pauza začala. Dopřejte si chvíli odpočinku.','good');}},{label:'Zavřít',fn:close=>close()}]);
  CI.initUI=()=>{
    CI.$$('.world-button').forEach(b=>b.addEventListener('click',()=>{CI.world=b.dataset.world;CI.render();}));
    CI.$$('.icon-button').forEach(b=>b.addEventListener('click',()=>({missions:CI.missionsModal,statistics:CI.statisticsModal,settings:CI.settingsModal}[b.dataset.action]||(()=>{}))()));
    CI.$('[data-action="save"]').addEventListener('click',CI.save);CI.$('[data-action="responsible"]').addEventListener('click',CI.responsibleModal);
    CI.$('#import-file').addEventListener('change',e=>{if(e.target.files&&e.target.files[0])CI.importSave(e.target.files[0]);e.target.value='';});
    CI.$$('.focus-toggle').forEach(button=>button.addEventListener('click',()=>{const panel=button.closest('.game-panel'),focused=panel.classList.toggle('focused-panel');document.body.classList.toggle('focus-mode',focused);CI.$('#focus-scrim').classList.toggle('hidden',!focused);button.textContent=focused?'×':'⤢';button.title=focused?'Zavřít zvětšenou hru':'Zaměřit hru';button.setAttribute('aria-label',button.title);}));
    CI.$('#focus-scrim').addEventListener('click',()=>CI.$('.focused-panel .focus-toggle')?.click());
    document.addEventListener('keydown',e=>{if(e.key==='Escape')CI.$('.focused-panel .focus-toggle')?.click();});
    document.addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(!b)return;const key=b.dataset.step,limits={slotBet:[10,500],slotLines:[10,20],blackjackBet:[10,1000]},[min,max]=limits[key];CI.state[key]=CI.checkedInteger(CI.state[key]+Number(b.dataset.delta),min,max);CI.$('#slot-lines').textContent=CI.state.slotLines;CI.render();});
  };
  CI.renderRivals=()=>{CI.$$('.rival-marker').forEach(e=>e.remove());(CI.state.rivals||[]).forEach((p,i)=>{const m=document.createElement('div');m.className='rival-marker';m.title=p.name+' • '+p.property+' • '+p.vehicle;m.textContent='♟';m.style.cssText=`position:absolute;z-index:5;left:${15+i*13}% ;top:${32+(i%3)*8}%;color:#e9d18d;font-size:21px;text-shadow:0 2px 3px #000`;CI.$('#city-map').append(m);});};
})();
