(function(){'use strict';
  const CI=window.CI,suits=['♠','♥','♦','♣'],ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
  let shoe=[],round=null;
  function shuffle(){shoe=[];for(let d=0;d<6;d++)for(const suit of suits)for(const rank of ranks)shoe.push({rank,suit});for(let i=shoe.length-1;i>0;i--){const j=CI.random(0,i);[shoe[i],shoe[j]]=[shoe[j],shoe[i]];}}
  function card(){if(shoe.length<26)shuffle();return shoe.pop();}
  function value(hand){let total=0,aces=0;hand.forEach(c=>{if(c.rank==='A'){total+=11;aces++;}else total+=['J','Q','K'].includes(c.rank)?10:Number(c.rank);});while(total>21&&aces){total-=10;aces--;}return total;}
  function renderCards(){if(!round)return;const d=CI.$('#dealer-hand'),p=CI.$('#player-hand');d.replaceChildren();p.replaceChildren();round.dealer.forEach((c,i)=>d.append(cardNode(c,round.active&&!round.reveal&&i===1)));const current=round.hands[round.activeHand];current.forEach(c=>p.append(cardNode(c)));CI.$('#dealer-score').textContent=round.reveal?value(round.dealer):round.dealer[0].rank+' + ?';CI.$('#player-score').textContent=value(current);
    const extra=CI.$('#split-hand');if(extra)extra.remove();if(round.hands.length>1){const area=document.createElement('div');area.id='split-hand';area.className='hand-area';area.innerHTML='<span class="hand-label">DRUHÁ RUKA <b>'+value(round.hands[1])+'</b></span><div class="cards"></div>';round.hands[1].forEach(c=>area.querySelector('.cards').append(cardNode(c)));CI.$('.blackjack-felt').append(area);}
    const active=round.active&&!round.insuranceOffer,buttons=['hit','stand','double','split'].map(a=>CI.$('[data-action="'+a+'"]'));buttons.forEach(b=>b.disabled=!active);CI.$('[data-action="double"]').disabled=!active||current.length!==2||round.doubled[round.activeHand]||CI.state.credits<round.bets[round.activeHand];CI.$('[data-action="split"]').disabled=!active||round.hands.length!==1||current.length!==2||rankValue(current[0].rank)!==rankValue(current[1].rank)||CI.state.credits<round.bets[0];CI.$('[data-action="deal"]').disabled=!!(round.active);CI.$('[data-action="insurance"]').hidden=!round.insuranceOffer;CI.$('[data-action="insurance"]').disabled=CI.state.credits<Math.floor(round.bets[0]/2);
  }
  function rankValue(r){return r==='A'?11:['J','Q','K'].includes(r)?10:Number(r);}
  function cardNode(c,hidden=false){const el=document.createElement('div');el.className='playing-card'+(hidden?' back':'')+(!hidden&&['♥','♦'].includes(c.suit)?' red':'');el.textContent=hidden?'':c.rank+c.suit;return el;}
  function start(){if(round&&round.active)return;const bet=CI.checkedInteger(CI.state.blackjackBet,10,1000),s=CI.state;if(!CI.canWager(bet)){CI.toast('Tato sázka překračuje váš limit hry nebo stav kreditů.','bad');return;}CI.placeWager(bet);s.blackjackRounds++;round={active:true,reveal:false,activeHand:0,hands:[[card(),card()]],dealer:[card(),card()],bets:[bet],doubled:[false],insuranceOffer:false,insured:0};CI.$('#blackjack-message').textContent='Karty jsou rozdány.';CI.saveSilent();renderCards();CI.sound(520,.1);
    if(round.dealer[0].rank==='A'){round.insuranceOffer=true;renderCards();CI.modal('Pojištění',`<p>Krupiér ukazuje eso. Pojistka stojí <b>${CI.money(Math.floor(bet/2))} kr.</b> a vyplatí se 2:1, pokud má krupiér blackjack.</p>`,[{label:'Pojistit ruku',kind:'gold-button',fn:close=>{insurance();close();}},{label:'Bez pojištění',fn:close=>{round.insuranceOffer=false;renderCards();close();resolveNaturals();}}]);}
    else resolveNaturals();
  }
  function insurance(){if(!round||!round.insuranceOffer)return;const cost=Math.floor(round.bets[0]/2);if(!CI.canWager(cost)){CI.toast('Pojištění překračuje váš limit hry nebo stav kreditů.','bad');return;}CI.placeWager(cost);round.insured=cost;round.insuranceOffer=false;renderCards();resolveNaturals();}
  function resolveNaturals(){if(!round)return;const dealerBlackjack=value(round.dealer)===21;if(dealerBlackjack){round.reveal=true;if(round.insured)CI.payCasino(round.insured*3);const playerNatural=value(round.hands[0])===21;if(playerNatural)CI.payCasino(round.bets[0]);finish(playerNatural?'Oba mají blackjack — sázka vrácena.':'Krupiér má blackjack. '+(round.insured?'Pojištění vyplatilo '+CI.money(round.insured*2)+' kr.':''));}else if(value(round.hands[0])===21){round.reveal=true;CI.payCasino(Math.floor(round.bets[0]*2.5*(1+CI.casinoBonus())));finish('Přirozený blackjack! Výplata 3:2.');}else renderCards();}
  function hit(){if(!round||!round.active||round.insuranceOffer)return;const hand=round.hands[round.activeHand];hand.push(card());CI.sound(430,.09);if(value(hand)>=21){renderCards();if(value(hand)>21)CI.$('#blackjack-message').textContent='Přes 21 — ruka prohrává.';nextHand();}else renderCards();}
  function stand(){if(!round||!round.active||round.insuranceOffer)return;nextHand();}
  function nextHand(){if(round.activeHand+1<round.hands.length){round.activeHand++;renderCards();return;}dealerPlay();}
  function double(){if(!round||!round.active)return;const i=round.activeHand;if(!CI.canWager(round.bets[i])){CI.toast('Zdvojnásobení překračuje váš limit hry nebo stav kreditů.','bad');return;}CI.placeWager(round.bets[i]);round.bets[i]*=2;round.doubled[i]=true;round.hands[i].push(card());renderCards();nextHand();}
  function split(){if(!round||!round.active||round.hands.length!==1)return;const hand=round.hands[0],rank=hand[0].rank;if(rankValue(rank)!==rankValue(hand[1].rank)||!CI.canWager(round.bets[0])){CI.toast('Rozdělení překračuje váš limit hry nebo stav kreditů.','bad');return;}CI.placeWager(round.bets[0]);round.hands.push([hand.pop()]);round.bets.push(round.bets[0]);round.doubled.push(false);round.hands[0].push(card());round.hands[1].push(card());round.split=true;renderCards();CI.$('#blackjack-message').textContent='Rozdělené ruce — hrajte první ruku.';}
  function dealerPlay(){if(round.hands.every(h=>value(h)>21)){round.reveal=true;finish('Všechny ruce překročily 21.');return;}round.reveal=true;renderCards();while(value(round.dealer)<17)round.dealer.push(card());const dealer=value(round.dealer);let payout=0,wins=0;round.hands.forEach((h,i)=>{const player=value(h);if(player<=21){if(dealer>21||player>dealer){payout+=Math.floor(round.bets[i]*2*(1+CI.casinoBonus()));wins++;}else if(player===dealer)payout+=round.bets[i];}});if(payout)CI.payCasino(payout);finish(dealer>21?'Krupiér překročil 21. '+wins+' vítězných rukou.':`Krupiér má ${dealer}. ${wins} vítězných rukou.`);}
  function finish(message){round.active=false;round.reveal=true;CI.$('#blackjack-message').textContent=message;renderCards();CI.saveSilent();CI.render();CI.toast(message,message.includes('výplata')||message.includes('blackjack')?'good':'');}
  CI.initBlackjack=()=>{shuffle();CI.$('[data-action="deal"]').addEventListener('click',start);CI.$('[data-action="hit"]').addEventListener('click',hit);CI.$('[data-action="stand"]').addEventListener('click',stand);CI.$('[data-action="double"]').addEventListener('click',double);CI.$('[data-action="split"]').addEventListener('click',split);CI.$('[data-action="insurance"]').addEventListener('click',insurance);};
})();
