(function(){'use strict';
  const CI=window.CI,order=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26],reds=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
  let angle=0,spinning=false;
  function draw(){const canvas=CI.$('#roulette-wheel'),ctx=canvas.getContext('2d'),cx=180,cy=180,r=168;ctx.clearRect(0,0,360,360);ctx.save();ctx.translate(cx,cy);ctx.rotate(angle);const step=Math.PI*2/37;
    order.forEach((n,i)=>{const start=-Math.PI/2+i*step,end=start+step;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,start,end);ctx.closePath();ctx.fillStyle=n===0?'#16834d':reds.has(n)?'#a72b29':'#171717';ctx.fill();ctx.strokeStyle='#d3b66a';ctx.lineWidth=1.5;ctx.stroke();ctx.save();ctx.rotate(start+step/2);ctx.translate(r-23,0);ctx.rotate(Math.PI/2);ctx.fillStyle='#f6e7c0';ctx.font='bold 12px Georgia';ctx.textAlign='center';ctx.fillText(String(n),0,4);ctx.restore();});
    ctx.beginPath();ctx.arc(0,0,52,0,Math.PI*2);ctx.fillStyle='#795a2e';ctx.fill();ctx.strokeStyle='#e5ca79';ctx.lineWidth=4;ctx.stroke();ctx.beginPath();ctx.arc(0,0,43,0,Math.PI*2);ctx.fillStyle='#183d2a';ctx.fill();ctx.restore();
  }
  function addBet(type,value=null){const amount=CI.state.selectedChip;if(CI.state.bets.roulette.length>=20){CI.toast('Na stole můžete mít nejvýše 20 žetonů.','bad');return;}CI.state.bets.roulette.push({type,value,amount});renderBets();CI.sound(440,.05);}
  function renderBets(){CI.$$('.roulette-number').forEach(b=>{const count=CI.state.bets.roulette.filter(x=>x.type==='straight'&&x.value===Number(b.dataset.number)).length;b.classList.toggle('selected-bet',count>0);b.title=count?'Počet žetonů: '+count:'';});CI.$$('#outside-bets [data-bet-type]').forEach(b=>b.classList.toggle('selected-bet',CI.state.bets.roulette.some(x=>x.type===b.dataset.betType&&x.value===(b.dataset.betValue?Number(b.dataset.betValue):null))));}
  function spin(){if(spinning)return;const bets=CI.state.bets.roulette;if(!bets.length){CI.toast('Nejprve položte alespoň jeden žeton na číslo.','bad');return;}const total=bets.reduce((sum,x)=>sum+x.amount,0);if(!CI.canWager(total)){CI.toast(CI.state.settings.cooldownUntil>Date.now()?'Pauza na zodpovědnou hru právě probíhá.':'Sázka překračuje váš limit hry nebo stav kreditů.','bad');return;}
    CI.placeWager(total);CI.state.rouletteRounds++;CI.saveSilent();const result=CI.pick(order),index=order.indexOf(result),step=Math.PI*2/37,target=-(index*step+step/2),normalized=((target-angle)%(Math.PI*2)+Math.PI*2)%(Math.PI*2),turns=6+CI.random(0,2),from=angle,to=angle+turns*Math.PI*2+normalized,started=performance.now(),duration=5200;spinning=true;CI.$('#roulette-result').textContent='Kolo se roztáčí…';CI.sound(180,.2,'sawtooth');
    function frame(now){const p=Math.min(1,(now-started)/duration),ease=1-Math.pow(1-p,4);angle=from+(to-from)*ease;draw();if(p<1)requestAnimationFrame(frame);else settle(result,bets,total);}
    requestAnimationFrame(frame);
  }
  function payout(bet,result){if(bet.type==='straight')return bet.value===result?36:0;if(result===0)return 0;if(bet.type==='red')return reds.has(result)?2:0;if(bet.type==='black')return !reds.has(result)?2:0;if(bet.type==='even')return result%2===0?2:0;if(bet.type==='odd')return result%2===1?2:0;if(bet.type==='low')return result<=18?2:0;if(bet.type==='high')return result>=19?2:0;if(bet.type==='dozen')return Math.ceil(result/12)===bet.value?3:0;if(bet.type==='column')return (3-result%3)%3+1===bet.value?3:0;return 0;}
  function settle(result,bets,total){const base=bets.reduce((sum,b)=>sum+b.amount*payout(b,result),0),winning=Math.floor(base*(1+CI.casinoBonus()));if(winning)CI.payCasino(winning);CI.state.bets.roulette=[];CI.saveSilent();CI.render();const color=result===0?'zelená':reds.has(result)?'červená':'černá';CI.$('#roulette-result').textContent='Padla '+result+' — '+color+'. '+(winning?'Výhra '+CI.money(winning)+' kreditů!':'Sázky '+CI.money(total)+' kreditů propadly.');CI.toast(winning?'Ruleta přinesla '+CI.money(winning)+' kreditů!':'Tentokrát vyhrála ruleta.',winning?'good':'');CI.sound(winning?740:250,.35);renderBets();spinning=false;}
  CI.initRoulette=()=>{draw();const board=CI.$('#roulette-board'),zero=document.createElement('button');zero.className='roulette-number zero';zero.textContent='0';zero.dataset.betType='straight';zero.dataset.betValue='0';board.append(zero);for(let col=0;col<12;col++){const group=document.createElement('div');group.className='roulette-column';for(const n of [col*3+3,col*3+2,col*3+1]){const b=document.createElement('button');b.className='roulette-number '+(reds.has(n)?'':'black');b.textContent=n;b.dataset.betType='straight';b.dataset.betValue=n;group.append(b);}board.append(group);}board.addEventListener('click',e=>{const b=e.target.closest('[data-bet-type]');if(b)addBet(b.dataset.betType,b.dataset.betValue?Number(b.dataset.betValue):null);});CI.$('#outside-bets').addEventListener('click',e=>{const b=e.target.closest('[data-bet-type]');if(b)addBet(b.dataset.betType,b.dataset.betValue?Number(b.dataset.betValue):null);});CI.$$('#roulette-chips [data-chip]').forEach(b=>b.addEventListener('click',()=>{CI.state.selectedChip=Number(b.dataset.chip);CI.$$('#roulette-chips [data-chip]').forEach(x=>x.classList.toggle('selected',x===b));CI.render();}));CI.$('[data-action="rouletteSpin"]').addEventListener('click',spin);CI.$('[data-action="rouletteClear"]').addEventListener('click',()=>{CI.state.bets.roulette=[];renderBets();});};
})();
