(function(){'use strict';
  const CI=window.CI;
  function bank(){
    const loans=CI.state.loans,loanRows=loans.length?loans.map((l,i)=>`<div class="modal-row"><span>Úvěr ${i+1}<br><small>Splatnost: ${new Date(l.dueAt).toLocaleString('cs-CZ')}</small></span><b>${CI.money(l.repayment)} kr.</b><button class="wood-button" data-repay="${i}">Splátka</button></div>`).join(''):'<p class="modal-copy">Nemáte žádný aktivní úvěr.</p>';
    CI.modal('Císařská banka',`<p class="modal-copy">Bezpečný úvěr s pevnou úrokovou sazbou a jasnou splatností. Při prodlení banka zabaví majetek.</p><div class="modal-row"><span>Dostupný úvěrový limit</span><b>${CI.money(Math.max(500,2000+CI.state.prestige*100))} kr.</b></div><label>Částka úvěru<select id="loan-amount" class="modal-select"><option value="500">500 kr.</option><option value="1000">1 000 kr.</option><option value="2500">2 500 kr.</option><option value="5000">5 000 kr.</option><option value="10000">10 000 kr.</option></select></label><label>Doba splácení<select id="loan-term" class="modal-select"><option value="24">24 hodin • 8 %</option><option value="48">48 hodin • 14 %</option><option value="72">72 hodin • 20 %</option><option value="96">96 hodin • 25 %</option></select></label><h3>Vaše úvěry</h3>${loanRows}`,[{label:'Požádat o úvěr',kind:'gold-button',fn:close=>{const amount=Number(CI.$('#loan-amount').value),term=Number(CI.$('#loan-term').value),limit=Math.max(500,2000+CI.state.prestige*100);if(amount>limit){CI.toast('Tato částka překračuje váš úvěrový limit.','bad');return;}const interest=term===24?0.08:term===48?0.14:term===72?0.20:0.25,repayment=Math.ceil(amount*(1+interest));CI.state.loans.push({amount,repayment,dueAt:Date.now()+term*3600000,term});CI.updateCredit(amount);CI.saveSilent();CI.render();close();CI.toast('Úvěr '+CI.money(amount)+' kr. byl schválen.','good');}},{label:'Zavřít',fn:close=>close()}]);
    CI.$$('[data-repay]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.repay),loan=CI.state.loans[i];if(CI.state.credits<loan.repayment){CI.toast('Na splacení úvěru nemáte dostatek kreditů.','bad');return;}CI.updateCredit(-loan.repayment);CI.state.loans.splice(i,1);CI.saveSilent();CI.render();CI.modalRootClear();CI.toast('Úvěr byl splacen.','good');}));
  }
  CI.bankModal=bank;
  CI.initBank=()=>{CI.$('[data-building="bank"]').addEventListener('click',bank);};
})();
