(function(){'use strict';
  const CI=window.CI,businesses=[
    {name:'Obchod s oděvy',price:3500,income:45,prestige:5},{name:'Restaurace a bar',price:12000,income:150,prestige:15},{name:'Autopůjčovna',price:38000,income:430,prestige:35},{name:'Zastavárna',price:95000,income:900,prestige:65},{name:'Pobočka kasina',price:260000,income:2300,prestige:120},{name:'Stavební firma',price:620000,income:5100,prestige:210},{name:'Taxislužba',price:145000, income:1250,prestige:85}
  ];
  CI.businessData=()=>CI.state.business===null?null:businesses[CI.state.business]||null;
  CI.businessModal=()=>{const owned=CI.businessData(),list=businesses.map((b,i)=>`<div class="modal-row"><span>${b.name}${CI.state.business===i?' • váš podnik':''}</span><b>${i===CI.state.business?'Vlastní':CI.money(b.price)+' kr.'}</b></div>`).join('');CI.modal('Podniky města',`<p class="modal-copy">${owned?`Provozujete podnik <b>${owned.name}</b>, který vydělává ${CI.money(owned.income)} kr. za den.`:'Vyberte si podnik, který bude posilovat vaše městské příjmy.'}</p>${list}`,owned?[{label:'Vybrat jiný podnik',kind:'gold-button',fn:close=>{close();CI.businessMarket();}}]:[{label:'Prohlédnout nabídky',kind:'gold-button',fn:close=>{close();CI.businessMarket();}}]);};
  CI.businessMarket=()=>{const choices=businesses.map((b,i)=>`<div class="modal-row"><span>${b.name}<br><small>Výnos ${CI.money(b.income)} kr./den • prestiž ${b.prestige}</small></span><b>${CI.money(b.price)} kr.</b><button class="wood-button" data-buy-business="${i}">${CI.state.business===i?'Vlastní':'Koupit'}</button></div>`).join('');CI.modal('Investiční nabídka',`<p class="modal-copy">Vlastnit lze vždy jeden podnik. Nový podnik nahradí současný; výnosy se změní následující den.</p>${choices}`);CI.$$('[data-buy-business]').forEach(button=>button.addEventListener('click',()=>{const i=Number(button.dataset.buyBusiness),b=businesses[i],old=CI.businessData();if(CI.state.business===i)return;const price=Math.max(0,b.price-(old?CI.marketValue(old.price):0));if(CI.state.credits<price){CI.toast('Na nákup podniku nemáte dostatek kreditů.','bad');return;}CI.updateCredit(-price);CI.state.business=i;CI.state.stats.businessBought++;CI.state.prestige+=b.prestige;CI.saveSilent();CI.render();CI.modalRootClear();CI.toast('Podnik '+b.name+' byl zakoupen.','good');}));};
  CI.initBusinesses=()=>{CI.$$('[data-action="business"]').forEach(b=>b.addEventListener('click',CI.businessModal));};
})();
