(function(){'use strict';
  const CI=window.CI;
  CI.marketMultiplier=()=>1+Math.sin(Date.now()/86400000)*.08+CI.state.day%5*.012;
  CI.marketValue=base=>Math.max(0,Math.floor(base*CI.marketMultiplier()*.58));
  CI.marketModal=()=>{const all=[{name:'Starožitné hodiny',price:420},{name:'Zlaté kapesní hodinky',price:950},{name:'Obraz císařské galerie',price:3100},{name:'Vzácná mince',price:7800}];const multiplier=CI.marketMultiplier(),inventory=CI.state.inventory;CI.modal('Obchodní pasáž',`<p class="modal-copy">Ceny se mění podle nálady trhu. Aktuální index: <b>${Math.round(multiplier*100)} %</b>.</p>${all.map(x=>`<div class="modal-row"><span>${x.name}</span><b>${CI.money(x.price*multiplier)} kr.</b><button class="wood-button" data-market="${x.price}">Koupit</button></div>`).join('')}<h3>Vaše sbírka</h3>${inventory.length?inventory.map((x,i)=>`<div class="modal-row"><span>${CI.escape(x.name)}</span><b>${CI.money(Math.floor(x.price*multiplier*.8))} kr.</b><button class="wood-button" data-sell="${i}">Prodat</button></div>`).join(''):'<p class="modal-copy">Vaše sbírka je zatím prázdná.</p>'}`);CI.$$('[data-market]').forEach(b=>b.addEventListener('click',()=>{const base=Number(b.dataset.market),cost=Math.ceil(base*multiplier);if(CI.state.credits<cost){CI.toast('Na tento předmět nemáte dostatek kreditů.','bad');return;}CI.updateCredit(-cost);CI.state.inventory.push({name:all.find(x=>x.price===base).name,price:base});CI.state.prestige+=1;CI.saveSilent();CI.render();CI.marketModal();CI.toast('Předmět byl uložen do vaší sbírky.','good');}));CI.$$('[data-sell]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.sell),item=CI.state.inventory[i];if(!item)return;const value=Math.floor(item.price*multiplier*.8);CI.updateCredit(value);CI.state.inventory.splice(i,1);CI.saveSilent();CI.render();CI.marketModal();CI.toast('Předmět byl prodán za '+CI.money(value)+' kr.','good');}));};
  CI.collectIncome=()=>{const s=CI.state,now=Date.now(),overdue=s.loans.filter(loan=>now>loan.dueAt);if(overdue.length){s.loans=s.loans.filter(loan=>now<=loan.dueAt);for(const loan of overdue){if(s.property.level>1)s.property.level--;else if(s.property.index>0){s.property.index--;s.property.level=10;}else if(s.business!==null)s.business=null;else if(s.vehicle>0)s.vehicle--;else{s.credits=0;s.loans=[];s.property={index:0,level:1};s.prestige=Math.floor(s.prestige/2);CI.toast('Bankrot: banka zabavila váš majetek a vypořádala dluhy.','bad');break;}}if(s.credits>0)CI.toast('Úvěr nebyl splacen včas. Banka zabavila část vašeho majetku.','bad');CI.saveSilent();}
    if(s.sharkLoan&&now>s.sharkLoan.dueAt){const penalty=Math.ceil(s.sharkLoan.amount*.1);s.sharkLoan.amount+=penalty;s.sharkLoan.dueAt=now+5*60*1000;s.prestige=Math.max(0,s.prestige-10);CI.toast('Lichvářský dluh po splatnosti narostl o '+CI.money(penalty)+' kr.','bad');CI.saveSilent();}
    const dayMs=5*60*1000,elapsed=Math.max(0,now-s.lastIncomeAt),days=Math.min(7,Math.floor(elapsed/dayMs));if(!days)return;let total=CI.passiveIncome()*days+(CI.businessData()?.income||0)*days;s.lastIncomeAt+=days*dayMs;s.day+=days;
    if(s.day%30<days){const tax=Math.min(s.credits,Math.floor(CI.passiveIncome()*2));if(tax){CI.updateCredit(-tax);CI.toast('Městská daň z nemovitosti: '+CI.money(tax)+' kr.','');}}
    if(s.day%7<days)CI.toast('Týdenní aukce je otevřena na radnici.','');
    if(total)CI.updateCredit(total);CI.saveSilent();CI.render();if(total)CI.toast('Denní příjem z majetku: '+CI.money(total)+' kr.','good');
  };
  CI.initEconomy=()=>{CI.$$('[data-action="market"]').forEach(b=>b.addEventListener('click',CI.marketModal));CI.$$('[data-action="tax"]').forEach(b=>b.addEventListener('click',()=>CI.modal('Městská pokladna',`<p class="modal-copy">Daň z nemovitosti se odvádí každých 30 městských dnů. Aktuální den: ${CI.state.day}. Další termín za ${30-CI.state.day%30} dnů.</p><div class="modal-row"><span>Odhad daně</span><b>${CI.money(CI.passiveIncome()*2)} kr.</b></div>`)));setInterval(CI.collectIncome,60000);};
})();
