(function(){'use strict';
  const CI=window.CI;
  const districts={
    centrum:{title:'VIP / Centrum',text:'Nejdražší adresa města. V okolí stojí císařská banka, luxusní obchody a samotné Casino Imperial.',action:()=>CI.propertyModal()},
    bohata:{title:'Bohatá čtvrť',text:'Udržované ulice, elegantní vily a dobré příležitosti pro nákup luxusního vozidla.',action:()=>CI.vehicleModal()},
    stredni:{title:'Střední čtvrť',text:'Rušné městské centrum s byty, restauracemi a množstvím pracovních příležitostí.',action:()=>CI.jobsModal()},
    chudinska:{title:'Chudinská čtvrť',text:'Skromné domky, nízké nájmy a nenápadné doupě lichvářů na konci ulice.',action:()=>CI.sharkModal()},
    prumysl:{title:'Průmyslová zóna',text:'Dílny, sklady a podniky čekají na odvážného majitele.',action:()=>CI.businessModal()}
  };
  function district(id){const d=districts[id];CI.modal(d.title,`<p class="modal-copy">${d.text}</p><div class="modal-row"><span>Vaše poloha</span><b>${CI.vehicleData().name}</b></div>`,[{label:id==='prumysl'?'Podniky':id==='chudinska'?'Navštívit doupě':'Prozkoumat nabídku',kind:'gold-button',fn:close=>{close();d.action();}},{label:'Zavřít',fn:close=>close()}]);}
  function auction(){const week=Math.floor(CI.state.day/7),claimed=CI.state.auctionWeek===week,open=CI.state.day%7<2&&!claimed,price=4200+CI.state.day%5*350;CI.modal('Týdenní aukce',`<p class="modal-copy">${claimed?'Tento týden jste již jednu dražbu vyhráli.':open?'V aukční síni právě probíhá týdenní dražba.':'Aukční síň se otevře na začátku dalšího městského týdne.'}</p><div class="modal-row"><span>Starožitný zlatý kapesní chronometr</span><b>${CI.money(price)} kr.</b></div><p class="modal-copy">Vítěz získá vzácný sběratelský předmět a 5 bodů prestiže.</p>`,open?[{label:'Přihodit '+CI.money(price)+' kr.',kind:'gold-button',fn:close=>{if(CI.state.credits<price){CI.toast('Na tuto nabídku nemáte dostatek kreditů.','bad');return;}CI.updateCredit(-price);CI.state.prestige+=5;CI.state.auctionWeek=week;CI.state.inventory.push({name:'Starožitný zlatý kapesní chronometr',price});CI.saveSilent();CI.render();close();CI.toast('Aukci jste vyhráli. Chronometr je váš!','good');}},{label:'Zavřít',fn:close=>close()}]:[{label:'Zavřít',fn:close=>close()}]);}
  CI.initMap=()=>{CI.$$('.district').forEach(b=>b.addEventListener('click',()=>district(b.dataset.district)));CI.$('[data-building="auction"]').addEventListener('click',auction);CI.$('[data-building="casino"]').addEventListener('click',()=>{CI.world='casino';CI.render();});CI.$$('.map-building').forEach(b=>b.addEventListener('click',e=>e.stopPropagation()));CI.$('.city-map').addEventListener('click',e=>{const b=e.target.closest('.map-building');if(!b){const rect=CI.$('.city-map').getBoundingClientRect(),pin=CI.$('.player-pin');pin.style.left=(Math.max(5,Math.min(90,(e.clientX-rect.left)/rect.width*100)))+'%';pin.style.top=(Math.max(5,Math.min(90,(e.clientY-rect.top)/rect.height*100)))+'%';}});};
})();
